services:
  content-filter-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    networks:
      - content-filter-network

  mitmproxy:
    build:
      context: .
      dockerfile: Dockerfile.mitmproxy
    ports:
      - "8090:8090"
      - "8081:8081"
    volumes:
      - ./.scripts:/scripts
      - ./certs:/home/mitmproxy/.mitmproxy
    restart: unless-stopped
    networks:
      - content-filter-network

networks:
  content-filter-network: